import CardProducts from "./CardProducts";
import image from "../assets/images/product.png";
import imagebone from "../assets/images/bone.png";
import imagecamiseta from "../assets/images/camiseta.png";
import category from "./Category";
export const ListaProducts = [
  {
    id: "1",
    disccount: "30",
    image: image,
    title: "Tênis",
    name: "Nike Kswiss V8p",
    price: "$200",
    newPrice: "$100",
    category: "tenis",
  },
  {
    id: "1",
    disccount: "30",
    image: image,
    title: "Tênis",
    name: "Nike Kswiss V8p",
    price: "$200",
    newPrice: "$100",
    category: "tenis",
  },
  {
    id: "1",
    disccount: "30",
    image: image,
    title: "Tênis",
    name: "Nike Kswiss V8p",
    price: "$200",
    newPrice: "$100",
    category: "tenis",
  },
  {
    id: "1",
    disccount: "30",
    image: image,
    title: "Tênis",
    name: "Nike Kswiss V8p",
    price: "$200",
    newPrice: "$100",
    category: "tenis",
  },
  {
    id: "1",
    disccount: "30",
    image: image,
    title: "Tênis",
    name: "Nike Kswiss V8p",
    price: "$200",
    newPrice: "$100",
    category: "tenis",
  },
  {
    id: "1",
    disccount: "30",
    image: image,
    title: "Tênis",
    name: "Nike Kswiss V8p",
    price: "$200",
    newPrice: "$100",
    category: "tenis",
  },
  {
    id: "1",
    disccount: "30",
    image: image,
    title: "Tênis",
    name: "Nike Kswiss V8p",
    price: "$200",
    newPrice: "$100",
    category: "tenis",
  },
  {
    id: "1",
    disccount: "30",
    image: image,
    title: "Tênis",
    name: "Nike Kswiss V8p",
    price: "$200",
    newPrice: "$100",
    category: "tenis",
  },
];

export const ListaBone = [
  {
    id: "2",
    disccount: "30",
    image: imagebone,
    title: "Boné",
    name: "Style cap",
    price: "$200",
    newPrice: "$100",
    category: "bone",
  },
  {
    id: "2",
    disccount: "30",
    image: imagebone,
    title: "Boné",
    name: "Style cap",
    price: "$200",
    newPrice: "$100",
    category: "bone",
  },
  {
    id: "2",
    disccount: "30",
    image: imagebone,
    title: "Boné",
    name: "Style cap",
    price: "$200",
    newPrice: "$100",
    category: "bone",
  },
];
export const ListaCamisetas = [
  {
    id: "3",
    disccount: "30",
    image: imagecamiseta,
    title: "Camiseta",
    name: "Camiseta styles white",
    price: "$200",
    newPrice: "$100",
    category: "camiseta",
  },
  {
    id: "3",
    disccount: "30",
    image: imagecamiseta,
    title: "Camiseta",
    name: "Camiseta styles white",
    price: "$200",
    newPrice: "$100",
    category: "camiseta",
  },
  {
    id: "3",
    disccount: "30",
    image: imagecamiseta,
    title: "Camiseta",
    name: "Camiseta styles white",
    price: "$200",
    newPrice: "$100",
    category: "camiseta",
  },
];

export const ListaGallery = [
  {
    id: "1",
    image: image,
    name: "Tênis",
  },
  {
    id: "1",
    image: image,
    name: "Tênis",
  },
  {
    id: "1",
    image: image,
    name: "Tênis",
  },
];
